INSERT INTO CARRO(ID, PLACA, MODELO, VERSION) VALUES(1, 'ABC-1234', 'Corsa', 0);
INSERT INTO CARRO(ID, PLACA, MODELO, VERSION) VALUES(2, 'DAB-2314', 'Marverick', 0);
INSERT INTO CARRO(ID, PLACA, MODELO, VERSION) VALUES(3, 'DEF-1242', 'Astra', 0);
